extends "res://scripts/scene_chunks/scene_chunk.gd"

const StretchGeneratorScript := preload("res://scripts/generation/stretch_generator.gd")
const CatalogScript := preload("res://scripts/generation/stretch_archetype_catalog.gd")
const NavigationGraphScript := preload("res://scripts/system/core/navigation_graph.gd")
const CapabilitiesScript := preload("res://scripts/generation/stretch_capabilities.gd")

const DEFAULT_SPEC_PATH := "res://data/generated_stretches/generated_teaching_channels_shelter_1_to_2.json"
const PARTY_IDS := ["aster", "peris", "endo"]
const FULL_HP := 100.0
const FULL_STAMINA := 100.0

@export var default_spec_path := DEFAULT_SPEC_PATH

var _config: Dictionary = {}
var _spec: Dictionary = {}
var _catalog := CatalogScript.new()
var _node_markers: Dictionary = {}
var _node_targets: Dictionary = {}
var _route_surfaces: Dictionary = {}
var _navigation_graph
var _content_marker_count := 0
var _route_choice := ""
var _route_phase := "unstarted"
var _completed_nodes: Array[String] = []
var _activated_routes: Array[String] = []
var _resources_collected := 0
var _shortcut_unlocked := false
var _shelter_reached := false
var _shelter_rested := false
var _last_outcome := ""
var _risky_damage_total := 0.0
var _atp_foraged := 0
var _pressure_taken := 0.0
var _rests_taken := 0
var _first_shelter_beat_fired := false
var _unsupported_placeholder_count := 0
var _active_loadout := "spotlight"
var _active_party: Array[String] = ["aster", "peris", "endo"]
var _active_capabilities: Dictionary = {}
var _enforce_stage := true
var _node_approach_used: Dictionary = {}
var _blocked_nodes: Array[String] = []

func configure_chunk(config: Dictionary) -> void:
	_config = config.duplicate(true)
	_load_spec_from_config()
	if _built:
		_clear_generated_children()
		_build_chunk()

func _build_chunk() -> void:
	_ensure_spec_loaded()
	_ensure_graybox_layout()
	_ensure_navigation_layout()
	_configure_navigation_graph()
	name = "GeneratedStretchChunk_%s" % str(_spec.get("id", "stretch"))
	_unsupported_placeholder_count = 0
	_content_marker_count = 0
	_node_markers.clear()
	_node_targets.clear()
	_route_surfaces.clear()
	_build_foundation()
	_build_generated_routes()
	_build_generated_nodes()
	_build_palette_legend()
	reset_preview_state()

func get_scene_title() -> String:
	_ensure_spec_loaded()
	return str(_spec.get("title", "Generated Stretch"))

func get_scene_help() -> String:
	_ensure_spec_loaded()
	var tier := str(_spec.get("source", {}).get("complexity_tier", "generated")).capitalize()
	var composition: Dictionary = _spec.get("composition", {})
	if bool(composition.get("uses_random_walk", false)):
		return "%s archetype stretch generated by a seeded random walk through archetype elements. Node labels expose the visited element and route graph from the saved JSON spec." % tier
	if bool(composition.get("has_nested", false)):
		return "%s archetype stretch with chained outputs and nested sub-archetypes. Route, content, shortcut, and shelter markers are built from the saved JSON spec." % tier
	return "%s archetype stretch. Safe route, risky direct route, resource beat, shortcut marker, and shelter arrival are built from the saved JSON spec." % tier

func get_default_character() -> String:
	return "aster"

func get_preview_character_state() -> Dictionary:
	return _full_party_state()

func get_preview_time_state() -> Dictionary:
	return {
		"day": 1,
		"time": 0.28,
		"advance_time": true,
		"show_time": true,
	}

func get_spawn_positions() -> Dictionary:
	_ensure_spec_loaded()
	var positions := {}
	var anchors: Dictionary = _spec.get("anchors", {})
	for char_id in PARTY_IDS:
		if anchors.has(char_id):
			positions[char_id] = _vec3(anchors[char_id], Vector3.ZERO)
	positions["entry"] = _anchor_position("entry")
	positions["exit_shelter"] = _anchor_position("exit_shelter")
	return positions

func get_preview_anchors() -> Dictionary:
	_ensure_spec_loaded()
	var result := {}
	var anchors: Dictionary = _spec.get("anchors", {})
	for key in anchors.keys():
		result[str(key)] = _vec3(anchors[key], Vector3.ZERO)
	return result

func get_world_slot() -> Dictionary:
	_ensure_spec_loaded()
	var slot: Dictionary = _spec.get("world_slot", {}).duplicate(true)
	if not slot.has("preview_party_preset"):
		slot["preview_party_preset"] = "full_party_full_health"
	if not slot.has("canonical_party"):
		slot["canonical_party"] = PARTY_IDS.duplicate()
	return slot

func get_generation_spec() -> Dictionary:
	_ensure_spec_loaded()
	return _spec.duplicate(true)

func get_graybox_state() -> Dictionary:
	_ensure_spec_loaded()
	_ensure_graybox_layout()
	return _graybox_state()

func get_preview_state() -> Dictionary:
	_ensure_spec_loaded()
	var generation := {
		"contract_id": "stretch_generation_v1",
		"spec_id": str(_spec.get("id", "")),
		"schema": str(_spec.get("schema", "")),
		"title": str(_spec.get("title", "")),
		"complexity_tier": str(_spec.get("source", {}).get("complexity_tier", "")),
		"resolved_budget": _spec.get("budget", {}).duplicate(true),
		"limitations": _spec.get("settings", {}).get("limitations", {}).duplicate(true),
		"world_slot": get_world_slot(),
		"palette_usage": _spec.get("palette_usage", {}).duplicate(true),
		"archetype_chain": _spec.get("archetype_chain", []).duplicate(true),
		"composition": _spec.get("composition", {}).duplicate(true),
		"graybox": _graybox_state(),
		"navigation": get_navigation_state(),
		"chain_count": int(_spec.get("composition", {}).get("chain_count", (_spec.get("archetype_chain", []) as Array).size())),
		"nested_archetype_count": int(_spec.get("composition", {}).get("nested_count", 0)),
		"nested_depth": int(_spec.get("composition", {}).get("nested_depth", 0)),
		"uses_random_walk": bool(_spec.get("composition", {}).get("uses_random_walk", false)),
		"walk_element_count": int(_spec.get("composition", {}).get("walk_element_count", 0)),
		"walk_archetype_count": int(_spec.get("composition", {}).get("walk_archetype_count", 0)),
		"node_count": _nodes().size(),
		"route_count": _routes().size(),
		"completed_nodes": _completed_nodes.duplicate(),
		"activated_routes": _activated_routes.duplicate(),
		"route_choice": _route_choice,
		"route_phase": _route_phase,
		"resources_collected": _resources_collected,
		"shortcut_unlocked": _shortcut_unlocked,
		"shelter_reached": _shelter_reached,
		"shelter_rested": _shelter_rested,
		"first_shelter_beat_fired": _first_shelter_beat_fired,
		"last_outcome": _last_outcome,
		"risky_damage_total": _risky_damage_total,
		"atp_foraged": _atp_foraged,
		"pressure_taken": _pressure_taken,
		"rests_taken": _rests_taken,
		"unsupported_placeholder_count": _unsupported_placeholder_count,
		"content_marker_count": _content_marker_count,
		"active_loadout": _active_loadout,
		"active_party": _active_party.duplicate(),
		"blocked_nodes": _blocked_nodes.duplicate(),
		"solution_path": get_active_solution_path(),
		"solution_summary": _spec.get("headless", {}).get("solution_summary", {}).duplicate(true),
	}
	return {
		"contract_id": "generated_stretch_chunk_v1",
		"spec_id": generation["spec_id"],
		"world_slot": generation["world_slot"],
		"preview_party_preset": "full_party_full_health",
		"route_choice": _route_choice,
		"route_phase": _route_phase,
		"shelter_reached": _shelter_reached,
		"shelter_rested": _shelter_rested,
		"shortcut_unlocked": _shortcut_unlocked,
		"first_shelter_beat_fired": _first_shelter_beat_fired,
		"last_outcome": _last_outcome,
		"risky_damage_total": _risky_damage_total,
		"atp_foraged": _atp_foraged,
		"pressure_taken": _pressure_taken,
		"rests_taken": _rests_taken,
		"unsupported_placeholder_count": _unsupported_placeholder_count,
		"active_loadout": _active_loadout,
		"blocked_nodes": _blocked_nodes.duplicate(),
		"solution_path": get_active_solution_path(),
		"graybox": generation["graybox"],
		"navigation": generation["navigation"],
		"generation": generation,
	}

func get_navigation_graph_data() -> Dictionary:
	_ensure_spec_loaded()
	_ensure_graybox_layout()
	_ensure_navigation_layout()
	return _spec.get("navigation", {}).duplicate(true)

## The unified-grid traversal layer (GridWorld.from_data contract): the preview installs this as the
## scene grid, so characters route on cells with per-cell route risk and ramp links across elevations.
## The semantic nodes/routes (the solver's and replay artifact's representation) are unchanged.
func get_grid_data() -> Dictionary:
	_ensure_spec_loaded()
	_ensure_graybox_layout()
	_ensure_navigation_layout()
	return _spec.get("navigation_grid", {}).duplicate(true)

func get_navigation_state() -> Dictionary:
	_ensure_spec_loaded()
	_ensure_navigation_layout()
	var nav_grid: Dictionary = _spec.get("navigation_grid", {})
	return {
		"contract_id": str(nav_grid.get("contract_id", "")),
		"walkable_cell_count": (nav_grid.get("walkable_cells", []) as Array).size(),
		"link_count": (nav_grid.get("links", []) as Array).size(),
		"level_count": int(nav_grid.get("level_count", 1)),
		"entry_node": str(nav_grid.get("entry_anchor", "")),
		"exit_node": str(nav_grid.get("exit_anchor", "")),
		"supports_multiple_elevations": bool(nav_grid.get("supports_multiple_elevations", false)),
		"elevation_indices": nav_grid.get("elevation_indices", []),
	}

func find_generated_path(from_position: Vector3, to_position: Vector3, mode := "safe") -> Array[Vector3]:
	_ensure_navigation_layout()
	if _navigation_graph == null:
		_configure_navigation_graph()
	if _navigation_graph == null:
		return []
	return _navigation_graph.find_path(from_position, to_position, mode)

func find_generated_node_path(from_node_id: String, to_node_id: String, mode := "safe") -> Array[String]:
	_ensure_navigation_layout()
	if _navigation_graph == null:
		_configure_navigation_graph()
	if _navigation_graph == null:
		return []
	return _navigation_graph.find_node_path(from_node_id, to_node_id, mode)

func get_generated_node_position(node_id: String) -> Vector3:
	_ensure_spec_loaded()
	var node := _find_node(node_id)
	if node.is_empty():
		return Vector3.INF
	return _vec3(node.get("position", []), Vector3.INF)

func reset_preview_state() -> void:
	_route_choice = ""
	_route_phase = "unstarted"
	_completed_nodes.clear()
	_activated_routes.clear()
	_resources_collected = 0
	_shortcut_unlocked = false
	_shelter_reached = false
	_shelter_rested = false
	_last_outcome = "ready"
	_risky_damage_total = 0.0
	_atp_foraged = 0
	_pressure_taken = 0.0
	_rests_taken = 0
	_first_shelter_beat_fired = false
	_node_approach_used.clear()
	_blocked_nodes.clear()
	set_active_loadout(_active_loadout)
	_restore_party()
	_set_preview_step("generated_stretch_ready")

## Choose which party is solving the stretch. "spotlight" is the full party (a
## specialist is on hand); "shadow" is the Aster+Peris pair. The active loadout's
## capabilities decide which approach each puzzle node accepts — and whether it blocks.
func set_active_loadout(loadout_id: String) -> void:
	var roster = _roster()
	for loadout in CapabilitiesScript.loadouts(roster):
		if str(loadout.get("id", "")) == loadout_id:
			_active_loadout = loadout_id
			_active_party.clear()
			for cid in loadout.get("party", []):
				_active_party.append(str(cid))
			_active_capabilities = (loadout.get("base_capabilities", {}) as Dictionary).duplicate()
			_enforce_stage = bool(loadout.get("enforce_stage", false))
			return
	# An unrecognised loadout id should never reach here (the only ids are spotlight/shadow);
	# warn rather than silently masquerade as spotlight, so a typo is caught instead of hidden.
	if loadout_id != "spotlight":
		push_warning("generated_stretch_chunk: unknown loadout '%s' — defaulting to spotlight" % loadout_id)
	_active_loadout = "spotlight"
	_active_party.clear()
	for cid in (CapabilitiesScript.normalize_roster(roster).get("enabled", []) as Array):
		_active_party.append(str(cid))
	_active_capabilities = CapabilitiesScript.roster_capabilities(roster)
	_enforce_stage = true


## The enabled roster this stretch was generated for (the enable/disable choices), read from
## the spec. Empty means the full canonical six.
func _roster():
	return _spec.get("source", {}).get("roster", _spec.get("settings", {}).get("roster", []))

## How far the player is assumed to have progressed — the first-play full party may only
## use techniques taught up to this stage. Read from the spec the generator produced.
func _progression_stage() -> int:
	return int(_spec.get("source", {}).get("progression_stage", _spec.get("settings", {}).get("progression_stage", 99)))

## The first approach the active party can field on this node, given its own
## capabilities plus any tool placed on the node. Marked blocked when none fit.
func _resolve_node_approach(node: Dictionary) -> Dictionary:
	var approaches: Array = node.get("approaches", [])
	if approaches.is_empty():
		return {"approach_id": "traverse", "kind": "traverse", "party": "any", "blocked": false}
	if _active_capabilities.is_empty():
		set_active_loadout(_active_loadout)
	var node_stage := int(node.get("stage", 1))
	var prog := _progression_stage()
	var available := _active_capabilities.duplicate()
	for tag in CapabilitiesScript.node_content_capabilities(node, _roster()).keys():
		available[tag] = true
	for approach in approaches:
		if not (approach is Dictionary):
			continue
		var ap := approach as Dictionary
		if _enforce_stage and int(ap.get("min_stage", node_stage)) > prog:
			continue  # technique not yet taught at this point in the campaign
		if CapabilitiesScript.requirements_met(ap.get("requires", []), available):
			var resolved := ap.duplicate()
			resolved["blocked"] = false
			return resolved
	return {"approach_id": "", "kind": "blocked", "party": "", "blocked": true}

func activate_generated_node(node_id: String) -> bool:
	_ensure_spec_loaded()
	var node := _find_node(node_id)
	if node.is_empty():
		_last_outcome = "missing_node:%s" % node_id
		return false
	var approach := _resolve_node_approach(node)
	if bool(approach.get("blocked", false)):
		if not _blocked_nodes.has(node_id):
			_blocked_nodes.append(node_id)
		_route_phase = "blocked"
		_last_outcome = "blocked:%s" % node_id
		_set_preview_step("generated_stretch_blocked")
		_show_note("%s has no way through %s." % [_active_loadout.capitalize(), str(node.get("title", node_id))], 2.0)
		return false
	_node_approach_used[node_id] = approach
	if not _completed_nodes.has(node_id):
		_completed_nodes.append(node_id)
	var role := str(node.get("role", ""))
	var survival := str(node.get("survival_kind", ""))
	match survival:
		"forage":
			_apply_forage_reward(node)
		"gauntlet", "hazard":
			_apply_node_pressure(node, approach)
		"exploit":
			_last_outcome = "exploit:%s" % str(node.get("exploit_target", "predator_prey"))
			_show_message("Turned the ecology against itself.", 1.0)
		"rest":
			_rests_taken += 1
			_restore_party()
			_show_message("Rested before dusk.", 1.0)
	# A plain (non-survival) resource beat is the full top-up; survival nodes did their own.
	if bool(node.get("resource", false)) and survival == "":
		_resources_collected += 1
		_restore_party()
		_show_message("Resource beat secured.", 1.0)
	if bool(node.get("shortcut", false)) or role == "shortcut":
		_shortcut_unlocked = true
		_show_message("Shortcut marked for return.", 1.0)
	if role == "shelter" or node_id == "exit_shelter":
		_reach_exit_shelter()
	else:
		_route_phase = "moving"
		_last_outcome = "node:%s" % node_id
		_set_preview_step("generated_stretch_%s" % node_id)
	_highlight_node(node_id, true)
	return true

func choose_generated_route(route_id: String, activate_target := true) -> bool:
	_ensure_spec_loaded()
	var route := _find_route(route_id)
	if route.is_empty():
		_last_outcome = "missing_route:%s" % route_id
		return false
	_route_choice = route_id
	if not _activated_routes.has(route_id):
		_activated_routes.append(route_id)
	var risk := _route_risk_value(route)
	var kind := _route_kind(route)
	if kind == "risky" or risk > 1:
		_apply_risky_pressure(risk, route)
		_route_phase = "recovering" if str(route.get("recovery", "")) != "" else "danger"
	elif kind == "shortcut":
		_shortcut_unlocked = true
		_route_phase = "shortcut"
	else:
		_route_phase = "moving"
	_last_outcome = "route:%s" % route_id
	_set_preview_step("generated_stretch_%s" % route_id)
	var target := str(route.get("to", ""))
	if activate_target and target != "":
		activate_generated_node(target)
	return true

func run_generated_golden_path() -> bool:
	_ensure_spec_loaded()
	reset_preview_state()
	set_active_loadout("spotlight")
	_route_phase = "golden"
	var path: Array = _spec.get("headless", {}).get("golden_path", [])
	if path.is_empty():
		path = ["entry", "exit_shelter"]
	for node_id in path:
		activate_generated_node(str(node_id))
	if not _shelter_rested and _blocked_nodes.is_empty():
		_reach_exit_shelter()
	_route_choice = "golden_path"
	return _shelter_rested

## The shadow solution: the same node spine solved by the Aster+Peris pair alone.
## Each puzzle node falls through to its shadow approach (no specialist on hand), so a
## completed shadow run is a genuinely different solution path than the golden run.
func run_generated_shadow_path() -> bool:
	_ensure_spec_loaded()
	reset_preview_state()
	set_active_loadout("shadow")
	_route_phase = "shadow"
	var path: Array = _spec.get("headless", {}).get("golden_path", [])
	if path.is_empty():
		path = ["entry", "exit_shelter"]
	for node_id in path:
		activate_generated_node(str(node_id))
	if not _shelter_rested and _blocked_nodes.is_empty():
		_reach_exit_shelter()
	_route_choice = "shadow_path"
	return _shelter_rested

## The approaches the active party actually used, in the order nodes were cleared —
## the data an in-game or Android replay animates.
func get_active_solution_path() -> Array:
	var path := []
	for node_id in _completed_nodes:
		var approach: Dictionary = _node_approach_used.get(node_id, {})
		path.append({
			"node": node_id,
			"approach_id": str(approach.get("id", approach.get("approach_id", ""))),
			"kind": str(approach.get("kind", "")),
			"party": str(approach.get("party", "")),
			"label": str(approach.get("label", "")),
			"risk": str(approach.get("risk", "")),
		})
	return path

func run_generated_risky_recovery() -> bool:
	_ensure_spec_loaded()
	reset_preview_state()
	var risky_found := false
	for route in _routes():
		if route is Dictionary and _route_kind(route as Dictionary) == "risky":
			risky_found = choose_generated_route(str((route as Dictionary).get("id", "")))
			break
	if not risky_found:
		_route_choice = "no_risky_route"
		_route_phase = "recovered"
	for node in _nodes():
		if node is Dictionary:
			var node_id := str((node as Dictionary).get("id", ""))
			if bool((node as Dictionary).get("resource", false)) or bool((node as Dictionary).get("shortcut", false)):
				activate_generated_node(node_id)
	_reach_exit_shelter()
	if _route_choice == "" or _route_choice == "no_risky_route":
		_route_choice = "risky_recovery"
	return _shelter_rested

## A failed traversal: the party commits to the risky route and takes the
## pressure, but is stranded short of the next shelter — the stretch is never
## crossed. Returns false (the run did not reach safety).
func run_generated_failed_traversal() -> bool:
	_ensure_spec_loaded()
	reset_preview_state()
	for route in _routes():
		if route is Dictionary and _route_kind(route as Dictionary) == "risky":
			choose_generated_route(str((route as Dictionary).get("id", "")), false)
			break
	if _route_choice == "":
		_route_choice = "failed_traversal"
	_route_phase = "failed"
	_shelter_reached = false
	_shelter_rested = false
	_last_outcome = "stranded"
	_set_preview_step("generated_stretch_failed")
	return _shelter_rested

func handle_preview_ability(ability_id: String, _ability: Dictionary = {}) -> Dictionary:
	match ability_id:
		"aster_focus":
			return {
				"message": "Aster reads the generated route.",
				"note": "Node labels and route colors expose the spec.",
				"state": "active",
				"duration": 0.35,
				"remaining": 0.35,
			}
		"peris_tune":
			return {
				"message": "Peris tunes the flora placeholders.",
				"note": "Unsupported flora remains visible as labeled graybox affordances.",
				"state": "active",
				"duration": 0.35,
				"remaining": 0.35,
			}
		"endo_patch":
			_shortcut_unlocked = true
			return {
				"message": "Endo marks the shortcut.",
				"note": "Shortcut state is now exposed in chunk preview state.",
				"state": "active",
				"duration": 0.35,
				"remaining": 0.35,
			}
	return {}

func _load_spec_from_config() -> void:
	var raw_spec: Variant = _config.get("spec", {})
	if raw_spec is Dictionary and not (raw_spec as Dictionary).is_empty():
		_spec = (raw_spec as Dictionary).duplicate(true)
		_ensure_graybox_layout()
		_ensure_navigation_layout()
		return
	var path := str(_config.get("spec_path", default_spec_path))
	var loaded := StretchGeneratorScript.load_spec(path)
	if not loaded.is_empty():
		_spec = loaded
		_ensure_graybox_layout()
		_ensure_navigation_layout()

func _ensure_spec_loaded() -> void:
	if not _spec.is_empty():
		return
	_config = {"spec_path": default_spec_path}
	_load_spec_from_config()
	if _spec.is_empty():
		_spec = StretchGeneratorScript.generate({
			"id": "generated_fallback_stretch",
			"title": "Generated Fallback Stretch",
			"seed": 1701,
			"complexity_tier": "teaching",
		})
	_ensure_graybox_layout()
	_ensure_navigation_layout()

func _clear_generated_children() -> void:
	for child in get_children():
		child.free()
	_interactables.clear()
	_node_markers.clear()
	_node_targets.clear()
	_route_surfaces.clear()

func _build_foundation() -> void:
	var graybox: Dictionary = _spec.get("graybox", {})
	var bounds: Dictionary = graybox.get("bounds", {})
	var bounds_center := _vec3(bounds.get("center", []), Vector3(12.0, 0.0, 0.0))
	var bounds_size := _vec3(bounds.get("size", []), Vector3(24.0, 3.0, 10.0))
	var min_point := _vec3(bounds.get("min", []), bounds_center - bounds_size * 0.5)
	var center := Vector3(bounds_center.x, min_point.y - 0.18, bounds_center.z)
	var size := Vector3(maxf(8.0, bounds_size.x + 8.0), 0.14, maxf(7.0, bounds_size.z + 5.0))
	_add_graybox_slab(self, center, size, Color(0.06, 0.072, 0.08), "GeneratedFoundation", Vector3.ZERO, true)
	_add_box(self, center + Vector3(0.0, 0.04, -size.z * 0.5), Vector3(size.x, 0.18, 0.16), Color(0.14, 0.16, 0.17))
	_add_box(self, center + Vector3(0.0, 0.04, size.z * 0.5), Vector3(size.x, 0.18, 0.16), Color(0.14, 0.16, 0.17))
	_add_label(self, str(_spec.get("title", "Generated Stretch")).to_upper(), Vector3(center.x, min_point.y + 3.0, min_point.z - 2.8), Color(0.78, 0.88, 0.94))
	_add_light(self, center + Vector3(0.0, 8.0, 0.0), Color(0.72, 0.86, 0.96), 1.25, maxf(34.0, bounds_size.x * 0.5))

func _build_generated_routes() -> void:
	for route in _routes():
		if not (route is Dictionary):
			continue
		var route_def := route as Dictionary
		var from_pos := _node_position(str(route_def.get("from", "")))
		var to_pos := _node_position(str(route_def.get("to", "")))
		if from_pos == Vector3.INF or to_pos == Vector3.INF:
			continue
		_build_route_segment(route_def, from_pos, to_pos)

func _build_route_segment(route: Dictionary, from_pos: Vector3, to_pos: Vector3) -> void:
	var middle := (from_pos + to_pos) * 0.5
	var delta := to_pos - from_pos
	var horizontal_length := maxf(0.8, sqrt(delta.x * delta.x + delta.z * delta.z))
	var width := maxf(0.4, float(route.get("width", route.get("surface", {}).get("width", 1.2))))
	var route_rotation := Vector3(0.0, atan2(delta.z, delta.x), -atan2(delta.y, horizontal_length))
	var route_box := _add_graybox_slab(
		self,
		middle + Vector3(0.0, 0.045, 0.0),
		Vector3(horizontal_length, 0.09, width),
		_route_color(route),
		"Route_%s" % str(route.get("id", "")),
		route_rotation,
		true
	)
	_route_surfaces[str(route.get("id", ""))] = route_box
	var label_pos := middle + Vector3(0.0, 0.82, 0.0)
	_add_label(self, "%s / R%d" % [_route_kind(route).to_upper(), _route_risk_value(route)], label_pos, _route_color(route).lightened(0.28))

func _build_generated_nodes() -> void:
	for node in _nodes():
		if not (node is Dictionary):
			continue
		_build_generated_node(node as Dictionary)

func _build_generated_node(node: Dictionary) -> void:
	var node_id := str(node.get("id", "node"))
	var pos := _node_position(node_id)
	if pos == Vector3.INF:
		return
	var role := str(node.get("role", "route"))
	var pad_size := _vec3(node.get("footprint", node.get("floor_size", [])), _node_pad_size(role))
	var highlight_meshes: Array[MeshInstance3D] = []
	var pad := _add_graybox_slab(self, pos + Vector3(0.0, -0.03, 0.0), pad_size, _role_color(role), "NodePad_%s" % node_id, Vector3.ZERO, true)
	highlight_meshes.append(pad)
	_build_elevation_posts(pos, pad_size, int(node.get("elevation_index", 0)), _role_color(role))
	var marker := _add_box(self, pos + Vector3(0.0, 0.48, 0.0), Vector3(1.35, 0.96, 1.35), _role_color(role).lightened(0.08), _role_color(role).lightened(0.22), 0.18, "NodeMarker_%s" % node_id)
	highlight_meshes.append(marker)
	_node_markers[node_id] = marker
	_add_label(self, str(node.get("title", node_id)).to_upper(), pos + Vector3(0.0, 1.78, 0.0), Color(0.88, 0.93, 0.95))
	highlight_meshes.append_array(_build_node_content_markers(node, pos))
	var approach := _vec3(node.get("approach_position", []), pos + Vector3(0.0, 0.0, pad_size.z * 0.34))
	var interactable := _add_inspection_interactable(
		self,
		"GeneratedNode_%s" % node_id,
		str(node.get("title", node_id)),
		approach + Vector3(0.0, 0.12, 0.0),
		"VISIT",
		"",
		1.8,
		false
	)
	interactable.interacted.connect(Callable(self, "activate_generated_node").bind(node_id))
	var target := _add_outline_target(
		self,
		"GeneratedNodeTarget_%s" % node_id,
		pos + Vector3(0.0, 0.58, 0.0),
		Vector3(maxf(1.8, pad_size.x), 1.35, maxf(1.8, pad_size.z)),
		highlight_meshes,
		node_id,
		interactable
	)
	_node_targets[node_id] = target

func _build_node_content_markers(node: Dictionary, pos: Vector3) -> Array[MeshInstance3D]:
	var meshes: Array[MeshInstance3D] = []
	var label_parts: Array[String] = []
	var placements: Array = node.get("content_placements", [])
	if not placements.is_empty():
		for raw_placement in placements:
			if not (raw_placement is Dictionary):
				continue
			var placement := raw_placement as Dictionary
			var category := str(placement.get("category", ""))
			var key := str(placement.get("id", ""))
			var support := str(placement.get("support", _catalog.support_level(category, key)))
			if support != "implemented":
				_unsupported_placeholder_count += 1
			var marker_pos := _vec3(placement.get("position", []), pos)
			var marker_size := _vec3(placement.get("size", []), Vector3(0.8, 0.8, 0.8))
			var marker := _add_content_marker(placement, marker_pos, marker_size, _content_color(category, support), "Generated_%s_%s" % [category, key])
			meshes.append(marker)
			_content_marker_count += 1
			_add_label(self, key.to_upper(), marker_pos + Vector3(0.0, marker_size.y * 0.55 + 0.34, 0.0), _content_color(category, support).lightened(0.25))
			label_parts.append("%s:%s" % [category.substr(0, 1), key])
		_add_content_summary_labels(node, pos, label_parts, placements.size())
		return meshes

	var offsets := [Vector3(-1.45, 0.35, -1.0), Vector3(1.45, 0.35, -1.0), Vector3(0.0, 0.35, 1.15)]
	var marker_index := 0
	for category in ["flora", "enemies", "structures"]:
		var values: Array = node.get(category, [])
		for value in values:
			var key := str(value)
			var marker_pos: Vector3 = pos + offsets[marker_index % offsets.size()] + Vector3(0.0, float(marker_index / offsets.size()) * 0.52, 0.0)
			var support := _catalog.support_level(category, key)
			if support != "implemented":
				_unsupported_placeholder_count += 1
			meshes.append(_add_box(self, marker_pos, Vector3(0.74, 0.58, 0.74), _content_color(category, support), Color.BLACK, 0.0, "Generated_%s_%s" % [category, key]))
			_content_marker_count += 1
			_add_label(self, key.to_upper(), marker_pos + Vector3(0.0, 0.72, 0.0), _content_color(category, support).lightened(0.25))
			label_parts.append("%s:%s" % [category.substr(0, 1), key])
			marker_index += 1
	var nested_values: Array = node.get("nested_archetypes", [])
	for nested_entry in nested_values:
		if not (nested_entry is Dictionary):
			continue
		var nested := nested_entry as Dictionary
		var nested_key := "A%s" % str(nested.get("id", "?"))
		var marker_pos: Vector3 = pos + offsets[marker_index % offsets.size()] + Vector3(0.0, float(marker_index / offsets.size()) * 0.52, 0.0)
		var nested_color := Color(0.42, 0.34, 0.62)
		meshes.append(_add_box(self, marker_pos, Vector3(0.74, 0.58, 0.74), nested_color, Color.BLACK, 0.0, "Generated_nested_%s" % str(nested.get("ref", nested_key))))
		_content_marker_count += 1
		_add_label(self, "%s S%d" % [nested_key, int(nested.get("host_step", 0))], marker_pos + Vector3(0.0, 0.72, 0.0), nested_color.lightened(0.25))
		label_parts.append("nest:%s" % nested_key)
		marker_index += 1
	var walk_element := str(node.get("walk_element", ""))
	if walk_element != "":
		var walk_color := Color(0.32, 0.48, 0.62)
		var marker_pos: Vector3 = pos + offsets[marker_index % offsets.size()] + Vector3(0.0, float(marker_index / offsets.size()) * 0.52, 0.0)
		meshes.append(_add_box(self, marker_pos, Vector3(0.74, 0.58, 0.74), walk_color, Color.BLACK, 0.0, "Generated_walk_%s" % str(node.get("walk_ref", node.get("id", "node")))))
		_content_marker_count += 1
		_add_label(self, "W%d S%d" % [int(node.get("walk_index", 0)) + 1, int(node.get("walk_step_index", 0)) + 1], marker_pos + Vector3(0.0, 0.72, 0.0), walk_color.lightened(0.25))
		label_parts.append("walk:%s" % str(node.get("walk_ref", "")))
		marker_index += 1
	if label_parts.is_empty():
		return meshes
	_add_label(self, " ".join(label_parts), pos + Vector3(0.0, 2.22, 0.0), Color(0.62, 0.7, 0.74))
	if walk_element != "":
		_add_label(self, walk_element, pos + Vector3(0.0, 2.78, 0.0), Color(0.68, 0.8, 0.88))
	return meshes

func _build_palette_legend() -> void:
	var usage: Dictionary = _spec.get("palette_usage", {})
	var legend := "Palette "
	var sections: Array[String] = []
	for category in ["flora", "enemies", "structures"]:
		sections.append("%s:%s" % [category, ",".join(_string_array(usage.get(category, [])))])
	legend += " | ".join(sections)
	_add_label(self, legend, _anchor_position("entry") + Vector3(6.5, 2.2, -3.4), Color(0.68, 0.74, 0.78))
	var composition: Dictionary = _spec.get("composition", {})
	if not composition.is_empty() and int(composition.get("chain_count", 0)) > 0:
		var composition_label := "Composition chain:%d nested:%d depth:%d" % [int(composition.get("chain_count", 0)), int(composition.get("nested_count", 0)), int(composition.get("nested_depth", 0))]
		if bool(composition.get("uses_random_walk", false)):
			composition_label = "Random walk elements:%d archetypes:%d" % [int(composition.get("walk_element_count", 0)), int(composition.get("walk_archetype_count", 0))]
		_add_label(
			self,
			composition_label,
			_anchor_position("entry") + Vector3(6.5, 2.75, -3.4),
			Color(0.74, 0.68, 0.84)
		)

func _ensure_graybox_layout() -> void:
	if _spec.is_empty():
		return
	var graybox: Dictionary = _spec.get("graybox", {})
	var nodes_have_placements := false
	for node in _spec.get("nodes", []):
		if node is Dictionary and (node as Dictionary).has("content_placements"):
			nodes_have_placements = true
			break
	if str(graybox.get("contract_id", "")) == "generated_stretch_graybox_v1" and nodes_have_placements:
		return

	var settings: Dictionary = _spec.get("settings", {})
	if not settings.is_empty():
		var regenerated := StretchGeneratorScript.generate(settings)
		if bool(regenerated.get("success", false)):
			for key in ["graybox", "nodes", "routes", "anchors"]:
				if regenerated.has(key):
					_spec[key] = regenerated.get(key)
			if regenerated.has("navigation"):
				_spec["navigation"] = regenerated.get("navigation")
			return

	_apply_local_graybox_fallback()

func _ensure_navigation_layout() -> void:
	if _spec.is_empty():
		return
	var navigation: Dictionary = _spec.get("navigation", {})
	var nav_grid: Dictionary = _spec.get("navigation_grid", {})
	if str(navigation.get("contract_id", "")) == "multi_level_navigation_graph_v1" \
			and str(nav_grid.get("contract_id", "")) == GridWorld.GRID_DATA_CONTRACT_ID:
		return
	var settings: Dictionary = _spec.get("settings", {})
	if not settings.is_empty():
		var regenerated := StretchGeneratorScript.generate(settings)
		if bool(regenerated.get("success", false)) and regenerated.has("navigation"):
			_spec["navigation"] = regenerated.get("navigation")
			_spec["navigation_grid"] = regenerated.get("navigation_grid", {})
			var graybox: Dictionary = _spec.get("graybox", {}).duplicate(true)
			graybox["navigation_contract_id"] = str(_spec.get("navigation", {}).get("contract_id", ""))
			graybox["navigation_node_count"] = int((_spec.get("navigation", {}).get("nodes", []) as Array).size())
			graybox["navigation_edge_count"] = int((_spec.get("navigation", {}).get("edges", []) as Array).size())
			_spec["graybox"] = graybox
			return
	_spec["navigation"] = StretchGeneratorScript.build_navigation_graph_from_spec(_spec)
	_spec["navigation_grid"] = StretchGeneratorScript.build_navigation_grid_from_spec(_spec)

func _configure_navigation_graph() -> void:
	var navigation: Dictionary = _spec.get("navigation", {})
	if navigation.is_empty():
		_navigation_graph = null
		return
	_navigation_graph = NavigationGraphScript.new()
	_navigation_graph.configure(navigation)

func _apply_local_graybox_fallback() -> void:
	var nodes: Array = _spec.get("nodes", [])
	var routes: Array = _spec.get("routes", [])
	var min_point := Vector3(1.0e20, 1.0e20, 1.0e20)
	var max_point := Vector3(-1.0e20, -1.0e20, -1.0e20)
	var elevations: Array[int] = []
	var placement_count := 0
	for i in range(nodes.size()):
		if not (nodes[i] is Dictionary):
			continue
		var node: Dictionary = nodes[i]
		var elevation_index := 0 if i == 0 or i == nodes.size() - 1 else i % 3
		var pos := _vec3(node.get("position", []), Vector3(float(i) * 12.0, 0.45, 0.0))
		pos.y = 0.45 + float(elevation_index) * 0.72
		var footprint := _node_pad_size(str(node.get("role", "mixed")))
		node["position"] = _vec3_array(pos)
		node["elevation_index"] = elevation_index
		node["surface_y"] = pos.y
		node["elevation_meters"] = pos.y - 0.45
		node["footprint"] = _vec3_array(footprint)
		node["floor_size"] = _vec3_array(footprint)
		node["approach_position"] = _vec3_array(pos + Vector3(0.0, 0.0, footprint.z * 0.34))
		node["content_placements"] = _fallback_content_placements(node, pos, footprint)
		placement_count += (node["content_placements"] as Array).size()
		nodes[i] = node
		if not elevations.has(elevation_index):
			elevations.append(elevation_index)
		var half := footprint * 0.5 + Vector3.ONE
		min_point = (pos - half) if i == 0 else min_point.min(pos - half)
		max_point = (pos + half + Vector3(0.0, 3.0, 0.0)) if i == 0 else max_point.max(pos + half + Vector3(0.0, 3.0, 0.0))
	for i in range(routes.size()):
		if not (routes[i] is Dictionary):
			continue
		var route: Dictionary = routes[i]
		route["width"] = 1.15 if _route_kind(route) == "risky" else 1.65
		routes[i] = route
	elevations.sort()
	_spec["nodes"] = nodes
	_spec["routes"] = routes
	_spec["anchors"] = _rebuild_anchors_from_nodes(nodes)
	_spec["graybox"] = {
		"contract_id": "generated_stretch_graybox_v1",
		"surface_y_base": 0.45,
		"elevation_step": 0.72,
		"elevation_indices": elevations,
		"elevation_count": elevations.size(),
		"supports_click_to_move": true,
		"supports_outline_targets": true,
		"supports_multiple_elevations": elevations.size() > 1,
		"node_surface_count": nodes.size(),
		"route_surface_count": routes.size(),
		"content_placement_count": placement_count,
		"bounds": {
			"min": _vec3_array(min_point),
			"max": _vec3_array(max_point),
			"center": _vec3_array((min_point + max_point) * 0.5),
			"size": _vec3_array(max_point - min_point),
		},
	}

func _fallback_content_placements(node: Dictionary, pos: Vector3, footprint: Vector3) -> Array:
	var placements := []
	var slot_index := 0
	for category in ["flora", "enemies", "structures"]:
		var values: Array = node.get(category, [])
		for value in values:
			var key := str(value)
			var size := _fallback_content_size(category)
			var offset := Vector3(-footprint.x * 0.22 + slot_index * 0.65, size.y * 0.5, -footprint.z * 0.16 + slot_index * 0.34)
			placements.append({
				"id": key,
				"category": category,
				"support": _catalog.support_level(category, key),
				"shape": "enemy_volume" if category == "enemies" else ("plant_cluster" if category == "flora" else "structure_box"),
				"size": _vec3_array(size),
				"local_offset": _vec3_array(offset),
				"position": _vec3_array(pos + offset),
				"rotation_y_degrees": float(slot_index * 31),
				"label": key,
			})
			slot_index += 1
	return placements

func _fallback_content_size(category: String) -> Vector3:
	match category:
		"flora":
			return Vector3(1.2, 1.0, 1.2)
		"enemies":
			return Vector3(1.4, 1.1, 1.4)
		"structures":
			return Vector3(1.6, 1.2, 1.0)
		_:
			return Vector3.ONE

func _rebuild_anchors_from_nodes(nodes: Array) -> Dictionary:
	var anchors: Dictionary = _spec.get("anchors", {}).duplicate(true)
	if not anchors.has("aster"):
		anchors["aster"] = [0.0, 0.5, 1.6]
	if not anchors.has("peris"):
		anchors["peris"] = [-1.6, 0.5, 0.0]
	if not anchors.has("endo"):
		anchors["endo"] = [-1.2, 0.5, -1.8]
	for node in nodes:
		if node is Dictionary:
			anchors[str((node as Dictionary).get("id", ""))] = (node as Dictionary).get("position", [0.0, 0.45, 0.0])
	return anchors

func _graybox_state() -> Dictionary:
	var graybox: Dictionary = _spec.get("graybox", {})
	var navigation: Dictionary = _spec.get("navigation", {})
	return {
		"contract_id": str(graybox.get("contract_id", "")),
		"navigation_contract_id": str(graybox.get("navigation_contract_id", navigation.get("contract_id", ""))),
		"supports_click_to_move": bool(graybox.get("supports_click_to_move", false)),
		"supports_outline_targets": bool(graybox.get("supports_outline_targets", false)),
		"supports_multiple_elevations": bool(graybox.get("supports_multiple_elevations", false)),
		"elevation_count": int(graybox.get("elevation_count", 0)),
		"node_surface_count": int(graybox.get("node_surface_count", _nodes().size())),
		"route_surface_count": int(graybox.get("route_surface_count", _routes().size())),
		"navigation_node_count": int(graybox.get("navigation_node_count", (navigation.get("nodes", []) as Array).size() if navigation.get("nodes", []) is Array else 0)),
		"navigation_edge_count": int(graybox.get("navigation_edge_count", (navigation.get("edges", []) as Array).size() if navigation.get("edges", []) is Array else 0)),
		"content_placement_count": int(graybox.get("content_placement_count", _content_marker_count)),
		"instanced_content_marker_count": _content_marker_count,
		"outline_target_count": _node_targets.size(),
		"route_surface_instance_count": _route_surfaces.size(),
		"bounds": graybox.get("bounds", {}).duplicate(true),
	}

func _add_graybox_slab(
	parent: Node3D,
	position: Vector3,
	size: Vector3,
	color: Color,
	node_name := "",
	rotation := Vector3.ZERO,
	add_collision := true
) -> MeshInstance3D:
	var mesh := _add_box(parent, position, size, color, color.lightened(0.08), 0.05, node_name)
	mesh.rotation = rotation
	if add_collision:
		var body := StaticBody3D.new()
		body.name = "%sCollision" % (node_name if node_name != "" else "GrayboxSlab")
		body.position = position
		body.rotation = rotation
		body.collision_layer = 1
		body.collision_mask = 0
		var collision := CollisionShape3D.new()
		var shape := BoxShape3D.new()
		shape.size = size
		collision.shape = shape
		body.add_child(collision)
		parent.add_child(body)
	return mesh

func _build_elevation_posts(pos: Vector3, pad_size: Vector3, elevation_index: int, color: Color) -> void:
	if elevation_index <= 0:
		return
	var post_height := maxf(0.24, pos.y - 0.28)
	var corners := [
		Vector3(-pad_size.x * 0.42, -post_height * 0.5 - 0.03, -pad_size.z * 0.42),
		Vector3(pad_size.x * 0.42, -post_height * 0.5 - 0.03, -pad_size.z * 0.42),
		Vector3(-pad_size.x * 0.42, -post_height * 0.5 - 0.03, pad_size.z * 0.42),
		Vector3(pad_size.x * 0.42, -post_height * 0.5 - 0.03, pad_size.z * 0.42),
	]
	for i in range(corners.size()):
		_add_box(self, pos + corners[i], Vector3(0.16, post_height, 0.16), color.darkened(0.22), Color.BLACK, 0.0, "ElevationPost_%d" % i)

func _add_content_marker(placement: Dictionary, marker_pos: Vector3, marker_size: Vector3, color: Color, node_name: String) -> MeshInstance3D:
	var shape := str(placement.get("shape", "structure_box"))
	var marker := MeshInstance3D.new()
	marker.name = node_name
	match shape:
		"plant_cluster", "canopy":
			var sphere := SphereMesh.new()
			sphere.radius = maxf(marker_size.x, marker_size.z) * 0.5
			sphere.height = marker_size.y
			marker.mesh = sphere
		"mat":
			var box := BoxMesh.new()
			box.size = marker_size
			marker.mesh = box
		"vine_column", "enemy_volume", "pipe":
			var cylinder := CylinderMesh.new()
			cylinder.top_radius = maxf(marker_size.x, marker_size.z) * 0.5
			cylinder.bottom_radius = cylinder.top_radius
			cylinder.height = marker_size.y
			cylinder.radial_segments = 12
			marker.mesh = cylinder
		_:
			var box := BoxMesh.new()
			box.size = marker_size
			marker.mesh = box
	marker.material_override = _make_material(color, color.lightened(0.15), 0.18 if str(placement.get("support", "")) == "implemented" else 0.06)
	marker.position = marker_pos
	marker.rotation.y = deg_to_rad(float(placement.get("rotation_y_degrees", 0.0)))
	add_child(marker)
	return marker

func _add_content_summary_labels(node: Dictionary, pos: Vector3, label_parts: Array[String], _placement_count: int) -> void:
	if label_parts.is_empty():
		return
	_add_label(self, " ".join(label_parts), pos + Vector3(0.0, 2.36, 0.0), Color(0.62, 0.7, 0.74))
	var walk_element := str(node.get("walk_element", ""))
	if walk_element != "":
		_add_label(self, walk_element, pos + Vector3(0.0, 2.92, 0.0), Color(0.68, 0.8, 0.88))

func _add_outline_target(
	parent: Node3D,
	target_name: String,
	center: Vector3,
	size: Vector3,
	meshes: Array[MeshInstance3D],
	node_id: String,
	delegate: Node
) -> StaticBody3D:
	# Build through the shared outline system so the target is actually bound to a
	# feedback manager in gameplay (it used to be orphaned here). Stretch tuning is
	# slimmer than the room default (smaller particle budget, taller highlight box).
	var metadata := {"generated_node_id": node_id}
	if delegate is Node3D:
		metadata["interaction_target_position"] = (delegate as Node3D).global_position
	var opts := {
		"outline_highlight_height": maxf(0.8, size.y * 0.5),
		"selected_feedback_duration": 1.4,
		"hover_object_outline_width": 0.075,
		"selected_object_glow_strength": 3.2,
		"selected_particle_count": 130,
		"outline_particles_per_mesh": 96,
		"debug_particle_anchor_enabled": false,
		"delegate": delegate,
		"metadata": metadata,
	}
	return _outline_target(parent, target_name, center, size, meshes,
		node_id, maxf(size.x, size.z) * 0.5, opts) as StaticBody3D

func _reach_exit_shelter() -> void:
	_shelter_reached = true
	_shelter_rested = true
	_route_phase = "complete"
	_last_outcome = "success"
	_first_shelter_beat_fired = true
	_restore_party()
	_highlight_node("exit_shelter", true)
	_set_preview_step("generated_stretch_complete")
	_show_note("Shelter reached and rested.", 2.5)

## Forage cache: bank a partial ATP top-up toward the next rest (GDD 2.4 — lysate adds
## whole pips up to the 8-pip cap). Not a full restore; the rest at the shelter is.
func _apply_forage_reward(node: Dictionary) -> void:
	var pips := int(node.get("atp_reward", 2))
	if pips <= 0:
		pips = 2
	_atp_foraged += pips
	for char_id in PARTY_IDS:
		_adjust_character_stat(char_id, "atp", float(pips))
	_route_phase = "forage"
	_last_outcome = "forage:+%d_atp" % pips
	_show_message("Banked %d ATP from the cache." % pips, 1.0)

## Gauntlet / attrition field: HP + stamina drain crossing it (recovered at the shelter).
## A specialist holding the lanes (or Endo building a protected lane) mitigates the
## attrition; the Aster+Peris pair pays the full price — the survival cost of the shadow.
func _apply_node_pressure(node: Dictionary, approach := {}) -> void:
	var damage := maxf(6.0, float(int(node.get("pressure_cost", 1))) * 8.0)
	if str(approach.get("party", "")) == "specialist":
		damage *= 0.4
	_pressure_taken += damage
	for char_id in PARTY_IDS:
		_adjust_character_stat(char_id, "hp", -damage)
		_adjust_character_stat(char_id, "stamina", -damage * 0.6)
	_route_phase = "attrition"
	_last_outcome = "pressure:%s" % str(node.get("survival_kind", "gauntlet"))
	_show_message("Attrition crossing the %s." % str(node.get("survival_kind", "gauntlet")), 1.0)

func _apply_risky_pressure(risk: int, route := {}) -> void:
	var damage := maxf(8.0, float(risk) * 8.0)
	if route is Dictionary and (route as Dictionary).has("damage"):
		damage = maxf(0.0, float((route as Dictionary).get("damage", damage)))
	_risky_damage_total += damage
	for char_id in PARTY_IDS:
		_adjust_character_stat(char_id, "hp", -damage)
		_adjust_character_stat(char_id, "stamina", -damage * 0.7)
	_last_outcome = "risky_pressure"
	_show_message("Risky route pressure applied.", 1.0)

func _restore_party() -> void:
	for char_id in PARTY_IDS:
		_set_character_stat(char_id, "hp", FULL_HP)
		_set_character_stat(char_id, "stamina", FULL_STAMINA)
		_set_character_stat(char_id, "atp", GameState.ATP_MAX_PIPS)
		_set_character_visible(char_id, true)
		_set_character_status(char_id, "")

func _highlight_node(node_id: String, selected: bool) -> void:
	var marker: MeshInstance3D = _node_markers.get(node_id, null)
	if marker == null:
		return
	var role_color := _role_color(str(_find_node(node_id).get("role", "")))
	marker.material_override = _make_material(
		role_color.lightened(0.26 if selected else 0.08),
		role_color.lightened(0.48),
		0.42 if selected else 0.18
	)

func _full_party_state() -> Dictionary:
	return {
		"aster": {"hp": FULL_HP, "stamina": FULL_STAMINA, "atp": GameState.ATP_MAX_PIPS, "visible": true},
		"peris": {"hp": FULL_HP, "stamina": FULL_STAMINA, "atp": GameState.ATP_MAX_PIPS, "visible": true},
		"endo": {"hp": FULL_HP, "stamina": FULL_STAMINA, "atp": GameState.ATP_MAX_PIPS, "visible": true},
	}

func _nodes() -> Array:
	_ensure_spec_loaded()
	return _spec.get("nodes", [])

func _routes() -> Array:
	_ensure_spec_loaded()
	return _spec.get("routes", [])

func _find_node(node_id: String) -> Dictionary:
	for node in _nodes():
		if node is Dictionary and str((node as Dictionary).get("id", "")) == node_id:
			return (node as Dictionary).duplicate(true)
	return {}

func _find_route(route_id: String) -> Dictionary:
	for route in _routes():
		if route is Dictionary and str((route as Dictionary).get("id", "")) == route_id:
			return (route as Dictionary).duplicate(true)
	return {}

func _anchor_position(anchor_id: String) -> Vector3:
	var anchors: Dictionary = _spec.get("anchors", {})
	if anchors.has(anchor_id):
		return _vec3(anchors[anchor_id], Vector3.ZERO)
	return _node_position(anchor_id)

func _node_position(node_id: String) -> Vector3:
	var node := _find_node(node_id)
	if not node.is_empty():
		return _vec3(node.get("position", []), Vector3.ZERO)
	var anchors: Dictionary = _spec.get("anchors", {})
	if anchors.has(node_id):
		var anchor := _vec3(anchors[node_id], Vector3.ZERO)
		return Vector3(anchor.x, 0.0, anchor.z)
	return Vector3.INF

func _vec3(raw: Variant, fallback: Vector3) -> Vector3:
	if raw is Vector3:
		return raw as Vector3
	if raw is Array and (raw as Array).size() >= 3:
		return Vector3(float((raw as Array)[0]), float((raw as Array)[1]), float((raw as Array)[2]))
	return fallback

func _vec3_array(value: Vector3) -> Array:
	return [value.x, value.y, value.z]

func _node_pad_size(role: String) -> Vector3:
	match role:
		"entry", "boundary":
			return Vector3(4.2, 0.12, 3.4)
		"shelter", "shelter_arrival":
			return Vector3(6.6, 0.14, 4.8)
		"pressure", "route_pressure", "danger":
			return Vector3(4.8, 0.12, 2.6)
		"shortcut":
			return Vector3(3.6, 0.12, 3.6)
		"foraging":
			return Vector3(4.8, 0.12, 3.8)
		"guidance":
			return Vector3(4.2, 0.12, 3.4)
		"setpiece":
			return Vector3(5.8, 0.12, 4.4)
		_:
			return Vector3(3.4, 0.12, 2.8)

func _role_color(role: String) -> Color:
	match role:
		"entry":
			return Color(0.18, 0.28, 0.34)
		"boundary":
			return Color(0.16, 0.22, 0.2)
		"resource", "foraging":
			return Color(0.18, 0.32, 0.2)
		"guidance":
			return Color(0.16, 0.25, 0.36)
		"pressure", "route_pressure", "danger":
			return Color(0.38, 0.16, 0.12)
		"shortcut":
			return Color(0.28, 0.22, 0.38)
		"setpiece":
			return Color(0.34, 0.26, 0.15)
		"shelter", "shelter_arrival":
			return Color(0.34, 0.27, 0.16)
		_:
			return Color(0.2, 0.22, 0.24)

func _route_color(route: Dictionary) -> Color:
	var kind := _route_kind(route)
	match kind:
		"risky":
			return Color(0.72, 0.24, 0.14)
		"safe":
			return Color(0.24, 0.48, 0.42)
		"shortcut":
			return Color(0.48, 0.36, 0.68)
		_:
			return Color(0.28, 0.34, 0.38)

func _route_kind(route: Dictionary) -> String:
	var kind := str(route.get("kind", ""))
	if kind != "":
		return kind
	return str(route.get("risk", "safe"))

func _route_risk_value(route: Dictionary) -> int:
	var raw: Variant = route.get("risk", route.get("kind", 0))
	if raw is int or raw is float:
		return int(raw)
	match str(raw):
		"risky":
			return 2
		"danger":
			return 2
		"safe":
			return 0
		"shortcut":
			return 0
		_:
			return 0

func _content_color(category: String, support: String) -> Color:
	if support != "implemented":
		return Color(0.46, 0.48, 0.5)
	match category:
		"flora":
			return Color(0.24, 0.56, 0.34)
		"enemies":
			return Color(0.68, 0.28, 0.18)
		"structures":
			return Color(0.36, 0.42, 0.52)
		_:
			return Color(0.5, 0.5, 0.5)

func _string_array(raw: Variant) -> Array[String]:
	var result: Array[String] = []
	if raw is Array:
		for value in raw:
			result.append(str(value))
	return result
