class_name WashRelayDressing
extends RefCounted

## The concept-plate detail pass for the wash_relay channels spiral, built SURVEY-FIRST
## (docs/SURVEY_REBUILD.md method). The GEOMETRY is Blender-authored like every modeled
## scene: `blender/channels/wash_dressing.blend` is the editable source, regenerated by
## `blender/channels/build_wash_dressing.py` and exported to
## `resources/models/channels/channels_dressing.glb` (the committed game asset). That
## build script mirrors THE SURVEY tables below — keep the two files in LOCKSTEP; every
## number traces to a measured datum (channels_arc.gd / channels.glb / wash_relay.tres)
## or a concept-plate ratio.
##
## This class is the RUNTIME half: it instantiates the GLB under a named "Dressing" root
## (a Node3D child -> survives the chunk's hide_flat_graybox) and wires the layers a baked
## model cannot carry:
##   - the rim OUTFALL sheets/foam (GLB nodes named `Fall_S<i>_<k>` / `Foam_S<i>_<k>` —
##     that name pattern is the build contract) get per-section animated materials and are
##     DRIVEN by the chunk's splash-intensity ease, so the falls pour exactly when (and as
##     hard as) each section floods — dressing never keeps time and never lies about the
##     cadence;
##   - the stencil sign TEXT (Label3D on the GLB's boards — crisp, data-side, wayfinding
##     only: goal + danger, never the solve);
##   - the two story-beat OmniLights (the lonely flure's warm pool, the curecumin gold).
## The beats' interactables (the target-less Flure, the dormant pad ring) are the chunk's.
##
## RECONCILIATION (plate -> helix), decided at the survey and baked into the build script:
## the plate's radial annulus maps onto the 1.27-turn ascending helix per element; the
## fattened central drum NECKS over the pressure-room band (the room occupies radius
## 0.6..5.0 at s 21..26.3, y ~3.6..7.4 — the visible break IS the story's "broken coil");
## the shaft wall is sparse pilaster fins (a full panel curtain occluded the deck);
## rim rails only span where nothing exits outward; plate worker figures and the walkable
## drum top were CUT (party frame / no-new-routes law).

const DRESSING_SCENE := "res://resources/models/channels/channels_dressing.glb"

# --- THE SURVEY: datums (mirrored by build_wash_dressing.py — keep in lockstep) ---------
const DECK_OUT_LANE := 4.0        # walkable rim (measured: FLOOR_Z_HALF)
const RIM_LANE := 4.45            # dressing strip just past the rim (outside walkable cells)
const INNER_RIM_LANE := -4.4      # inner dressing strip (walkable cells end at lane -4)
const S_MIN := -1.0               # floor_min_x (wash_relay.tres)
const S_MAX := 87.0               # floor_max_x

# Central drum (plate: unit D = 2 * DRUM_R; courses ~0.2 D; portholes; the spoked
# wheel-window faces the start shelter). Radius clears the beat ledges (inner radius 3.6)
# and the pressure-room band by necking between DRUM_NECK_Y0..Y1.
const DRUM_R := 3.45
const DRUM_NECK_Y0 := 3.0
const DRUM_NECK_Y1 := 7.6
const DRUM_TOP := 16.5

# Sector gates (plate: giant color-coded slab doors at the perimeter, one per section;
# the sluice's gate stands farther out — its outer tunnel bulge owns lanes 12-13).
const GATE_LANE := 12.6
const GATE_SLUICE_LANE := 14.6
const GATE_NUMERAL_Y := 4.2

# Rim outfalls (plate: fall width = its channel; here segmented like the flood water and
# slaved to each section's splash intensity).
const FALL_LANE := 4.55
const FALL_DROP := 5.2

# Shaft pilaster fins (depth cues at radius 23; the sluice tunnel's outer bulge owns
# s ~33..47 — no fin there).
const WALL_LANE := 12.0

# Story-beat ledges (chunk-owned walkable spurs; the chunk's BEAT_LEDGE_REGIONS match).
const FLURE_LEDGE_S := 62.5
const FLURE_POS_LANE := -6.4
const PAD_LEDGE_S := 1.6
const PAD_POS_LANE := -6.2

# Palette roles kept at runtime (labels + lights; the mesh palette lives in the .py).
const COL_TERM_GREEN := Color(0.36, 0.91, 0.5)     # #5ce87f
const COL_WATER_EM := Color(0.3, 0.75, 0.95)
const COL_GOLD := Color(0.95, 0.75, 0.15)          # Curecumin turmeric
const COL_STENCIL := Color(0.82, 0.8, 0.72)
const COL_CAUTION := Color(0.95, 0.6, 0.2)

static var _mat_cache: Dictionary = {}

# --- Entry ------------------------------------------------------------------------------

## Instantiate the Blender-authored dressing and wire the runtime layers. Returns the
## handle the chunk keeps: {"root", "falls" (per section), "foam", "mats"}. Missing GLB
## (unimported checkout) degrades to an empty-but-valid handle — never a hard fail.
static func build(chunk: Node3D, sections: Array) -> Dictionary:
	var root := Node3D.new()
	root.name = "Dressing"
	chunk.add_child(root)
	var sheets: Array = []
	var foam: Array = []
	var mats: Array = []
	for _i in range(sections.size()):
		sheets.append([])
		foam.append([])
		mats.append(_fall_material())
	if ResourceLoader.exists(DRESSING_SCENE):
		var packed: PackedScene = load(DRESSING_SCENE)
		if packed != null:
			var model := packed.instantiate() as Node3D
			model.name = "DressingModel"
			root.add_child(model)
			_collect_falls(model, sheets, foam, mats)
	_add_sign_labels(root, sections)
	_add_beat_lights(root)
	return {"root": root, "falls": sheets, "foam": foam, "mats": mats}

## Slave one section's outfall to the chunk's splash intensity (called from the existing
## per-frame splash ease — dressing keeps no clock of its own). intensity 0..1.
static func drive_falls(dressing: Dictionary, section: int, intensity: float) -> void:
	var mats: Array = dressing.get("mats", [])
	var sheets: Array = dressing.get("falls", [])
	var foam: Array = dressing.get("foam", [])
	if section >= mats.size():
		return
	var vis := intensity > 0.04
	for mi in sheets[section]:
		if is_instance_valid(mi):
			mi.visible = vis
	for mi in foam[section]:
		if is_instance_valid(mi):
			mi.visible = intensity > 0.45
	var m: StandardMaterial3D = mats[section]
	if m != null:
		m.alpha_scissor_threshold = lerpf(0.92, 0.3, clampf(intensity, 0.0, 1.0))
		m.emission_energy_multiplier = 2.6 * intensity

static func reset_falls(dressing: Dictionary) -> void:
	for i in range(int(dressing.get("mats", []).size())):
		drive_falls(dressing, i, 0.0)

# --- The GLB fall/foam contract ---------------------------------------------------------

## Walk the imported model for `Fall_S<i>_<k>` / `Foam_S<i>_<k>` meshes: falls get their
## section's animated material instance; both start hidden (the splash ease reveals them).
static func _collect_falls(model: Node3D, sheets: Array, foam: Array, mats: Array) -> void:
	var stack: Array = [model]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		for c in n.get_children():
			stack.push_back(c)
		if not (n is MeshInstance3D):
			continue
		var idx := _name_section(n.name, "Fall_S")
		if idx >= 0 and idx < sheets.size():
			(n as MeshInstance3D).material_override = mats[idx]
			(n as MeshInstance3D).visible = false
			(sheets[idx] as Array).append(n)
			continue
		idx = _name_section(n.name, "Foam_S")
		if idx >= 0 and idx < foam.size():
			(n as MeshInstance3D).visible = false
			(foam[idx] as Array).append(n)

static func _name_section(node_name: String, prefix: String) -> int:
	if not node_name.begins_with(prefix):
		return -1
	var rest := node_name.substr(prefix.length())
	var cut := rest.find("_")
	var digits := rest.substr(0, cut) if cut > 0 else rest
	return int(digits) if digits.is_valid_int() else -1

## Per-section INSTANCE (drive_falls animates threshold/energy independently). Streaky
## alpha texture + ALPHA_SCISSOR — never alpha BLEND (the preview drops the blended pass;
## the overlay-materials law).
static func _fall_material() -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = Color(0.55, 0.85, 0.95)
	m.albedo_texture = _streak_texture()
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_SCISSOR
	m.alpha_scissor_threshold = 0.92
	m.emission_enabled = true
	m.emission = COL_WATER_EM
	m.emission_energy_multiplier = 0.0
	m.roughness = 0.35
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	return m

static func _streak_texture() -> ImageTexture:
	if _mat_cache.has("streak_tex"):
		return _mat_cache["streak_tex"]
	var img := Image.create(48, 96, false, Image.FORMAT_RGBA8)
	var rng := RandomNumberGenerator.new()
	rng.seed = 4727
	for x in range(48):
		var col := 0.35 + 0.65 * rng.randf()
		if rng.randf() < 0.2:
			col = 0.0
		for y in range(96):
			var a := clampf(col + (rng.randf() - 0.5) * 0.35, 0.0, 1.0)
			img.set_pixel(x, y, Color(1.0, 1.0, 1.0, a))
	var tex := ImageTexture.create_from_image(img)
	_mat_cache["streak_tex"] = tex
	return tex

# --- Runtime sign text (the GLB carries the boards; text stays data-side and crisp) -----

const SECTION_TAGS := {
	"flush": "FLUSH", "current": "CURRENT", "jet": "JET", "plate": "PLATE",
	"sluice": "SLUICE", "patrol": "PATROL", "lure": "LURE", "basin": "BASIN",
	"double_plate": "PLATES",
}

static func _add_sign_labels(root: Node3D, sections: Array) -> void:
	var signs := Node3D.new()
	signs.name = "SignText"
	root.add_child(signs)
	# Positions mirror build_wash_dressing.py's RE-RECONCILED board spots (the survey
	# moved them clear of every walkable spur) — keep in lockstep.
	for i in range(sections.size()):
		var tag: String = SECTION_TAGS.get(str(sections[i]["type"]), "")
		_label(signs, float(sections[i]["x0"]) + 1.0, RIM_LANE,
			"S-%02d %s" % [i + 1, tag], COL_STENCIL, true)
	_label(signs, 4.6, INNER_RIM_LANE, "^ FLOW UP", COL_TERM_GREEN, false)
	for mid in [12.5, 28.5, 54.5, 62.5, 72.5]:
		_label(signs, float(mid) - 3.0, RIM_LANE, "MAINTENANCE", COL_STENCIL, true)
	_label(signs, 77.0, RIM_LANE, "CAUTION // DRAIN", COL_CAUTION, true)
	_label(signs, 60.2, INNER_RIM_LANE, "CAUTION // LEDGE", COL_CAUTION, false)
	_label(signs, 3.9, INNER_RIM_LANE, "CURECUMIN ROUTE", COL_GOLD, false)
	# The sector-gate stencil numerals (the GLB carries the colored slabs; text stays crisp
	# here). SECTOR + zero-padded index, big, pale — the plate's gate grammar.
	for i in range(sections.size()):
		var mid := (float(sections[i]["x0"]) + float(sections[i]["x1"])) * 0.5
		var lane := GATE_SLUICE_LANE if str(sections[i]["type"]) == "sluice" else GATE_LANE
		_label(signs, mid, lane - 0.45, "SECTOR\n%02d" % (i + 1), COL_STENCIL, true,
			GATE_NUMERAL_Y, 0.011, 64)

## Flush (non-billboard) stencil text riding the GLB board at the same survey spot.
static func _label(parent: Node3D, s: float, lane: float, text: String,
		tint: Color, face_inward: bool, y_off := 1.28, pix := 0.006, fsize := 40) -> void:
	var label := Label3D.new()
	label.text = text
	label.modulate = tint
	label.pixel_size = pix
	label.font_size = fsize
	label.outline_size = 6
	# Single-sided: a stencil read from behind must vanish, never render mirrored.
	label.double_sided = false
	var xf := _xf(s, lane, y_off)
	xf.origin += xf.basis.x * (-0.06 if face_inward else 0.06)
	label.transform = xf
	label.rotate_object_local(Vector3.UP, PI * 0.5 if face_inward else -PI * 0.5)
	parent.add_child(label)

# --- The two story-beat lights (the payoff glows; geometry + interactables elsewhere) ---

static func _add_beat_lights(root: Node3D) -> void:
	var warm := OmniLight3D.new()
	warm.light_color = Color(1.0, 0.62, 0.25)
	warm.light_energy = 1.6
	warm.omni_range = 7.0
	warm.position = ChannelsArc.arc_pos(FLURE_LEDGE_S, FLURE_POS_LANE) + Vector3(0.0, 1.0, 0.0)
	root.add_child(warm)
	var gold := OmniLight3D.new()
	gold.light_color = COL_GOLD
	gold.light_energy = 1.1
	gold.omni_range = 5.5
	gold.position = ChannelsArc.arc_pos(PAD_LEDGE_S, PAD_POS_LANE) + Vector3(0.0, 0.9, 0.0)
	root.add_child(gold)

# --- Placement (author FLAT (s, lane), warp through ChannelsArc) ------------------------

static func _xf(s: float, lane: float, y_off := 0.0) -> Transform3D:
	var xf := Transform3D(ChannelsArc.basis_at(s), ChannelsArc.arc_pos(s, lane))
	xf.origin += xf.basis.y * y_off
	return xf
